services:
  # Base de données PostgreSQL
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resonate_user -d resonate"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Interface d'administration pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - backend_db
      - frontend_backend
    depends_on:
      db:
        condition: service_healthy

  # Backend FastAPI
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend_backend
      - backend_internet
      - backend_db

  # Frontend React
  frontend:
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - frontend_backend
    volumes:
      - .:/app
      - /app/node_modules

  # Reverse proxy HTTPS
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - frontend_backend

# Volumes
volumes:
  postgres_data:
  pgadmin_data:

# Réseaux
networks:
  frontend_backend:
    driver: bridge
  backend_internet:
    driver: bridge
  backend_db:
    driver: bridge
    internal: true